# Generated by Django 3.0 on 2019-12-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_replycomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
