# Generated by Django 3.0 on 2019-12-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_replycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
