# Generated by Django 3.0 on 2019-12-18 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_replycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bloglikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blogviews',
        ),
        migrations.CreateModel(
            name='Hitslike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitcount', models.IntegerField(default=0)),
                ('viewcount', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
